#
# This is the Snakemake configuration file that specifies paths and 
# and options for the mapping pipeline
#

{
    # py2 is a hack so that python2 scripts can be called
    # by snakemake (which is written in python3). The value should
    # be a command to do whatever is needed to setup a python2 environment and
    # call the python2 interpreter. Depending on your system configuration,
    # this might involve setting the PATH environment variable or
    # just calling python2
    # "py2" : "PATH=$HOME/anaconda2/bin:$PATH; python ",
    "py2" : "PATH=/home/t.v.schaik/mydata/miniconda3/envs/WASP_python2/bin:$PATH; python ",
    # "py2" : "/home/t.v.schaik/mydata/miniconda3/envs/WASP_python2/bin/python",

    # WASP directory containing scripts
    "wasp_dir" : "/home/t.v.schaik/mydata/src/WASP",

    # directory to write all output data files to
    "output_dir" :  "WASP_ts190215_newparsing",

    # location of chromInfo file containing chromosome names and lengths
    # (can be downloaded from UCSC genome browser)
    "chrom_info" : "/home/t.v.schaik/mydata/data/genomes/mm10/mm10.chrom.sizes",

    # directory to read VCF files from (used to write SNP input files)
    # "vcf_dir" : "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/WASP",
    "vcf_dir" : "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/WASP",
    
    # OLD way: directory to write SNP plain text input files to
    "snp_dir" : "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/WASP/SNP_tables",

    # directory to write SNP HDF5 input files to
    "snp_h5_dir" : "WASP_output/SNPs",

    # path to samtools
    "samtools" : "samtools",

    # path to bowtie2 aligner
    "bowtie2" : "bowtie2",

    # prefix for bowtie2 reference genome index
    "bowtie2_index" : "/home/t.v.schaik/mydata/data/genomes/mouse_assemblies/bowtie2_index/GRCm38_68",
    # "bowtie2_index" : "/home/t.v.schaik/mydata/data/genomes/mm10/mm10",

    # sample file containing sample names and paths to fastq files
    "sample_file" : "samples_newparsing.txt"
}
